# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10571dd64f2307fb0da8dc7d8803b7fedab6072bb6eb25a9692acab5da9e820d635bca58d383d11f69cf5dc39e58377ca869cb8b193aab5c8dce3294f15449e8

test:
  secret_key_base: f18e04c2f833a698b2032373dc798cbff1cdb55ec843e14ada098ce329386c38d430e5ac0ff20aa73cc7f424e988685985825af9991a203adfe6c73f36977607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
